### ISSUE TITLE
Use Annotated pattern for aliasing field names

### ISSUE THREAD

**Issue by kongzii** [cowdao-grants/cow-py#28]
In https://github.com/cowdao-grants/cow-py/pull/26, we set `model_config = ConfigDict(populate_by_name=True)` so we can initialise pydantic models by non-aliased field names (because for example `from` is Python-reserved keyword and can not be used).

Currently, there are some type: ignores in the code because of that, because Pyright doesn't understand that property, [for example here](https://github.com/cowdao-grants/cow-py/pull/26/files#diff-f930358f2ad7bd5c5534db9261c5ae933a1051178a69370936d497a60b820195R63).

Solution should be using `from_: Annotated[Optional[Address], Field(None, alias=str('from'))]` instead of `from_: Optional[Address] = Field(None, alias="from")`, but that creates some additional issues that need to be solved, see [here](https://github.com/cowdao-grants/cow-py/pull/26#discussion_r1926765987).

**Comment by 8ball030** [comment]
@kongzii I believe that this is resolved.
Effectively i set this as a config option and we have an idiompotent build now. 
Would you mind confirming?

**Comment by kongzii** [comment]
Hey, I still see the type ignores, for example, in https://github.com/cowdao-grants/cow-py/blob/d13a5633df52a704751226b9e546b4fa32556c5c/cowdao_cowpy/cow/swap.py#L65. But I don't mind if you want to close this as low prio.

**Comment by 8ball030** [comment]
Ah I understand what you mean now. 
I think the underscore resolves that though right?

**Comment by 8ball030** [comment]
@kongzii I understand this more fully now,


So it turns out there is a flag in the auto generation tool. `use_annotations`

However, this causes a massive amount of failures inthe type checking as all of the Literals are no longer valid.
